#!/bin/sh

# If argument list equal to zero, quit.
[ "$#" -eq 0 ] && { printf "Link to channel(s) not provided\n"; exit 1; }

[ "$@" = "-h" ] || [ "$@" = "--help" ] && { \
    printf "%s: Convert YouTube channel link to RSS feed format.\n\n" "$0";
    printf "%s [link] [link 2] [link 3] ...\n" "$0";
	exit 0; \
}

for URL in "$@"; do
	CHANNEL_ID=$( \
        curl -s "$URL" \
        | sed -e 's/[{}]/''/g' \
        | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' \
        | grep -m 1 'channelId' \
        | sed \
            -e 's/header\"\:\"c4TabbedHeaderRenderer\"\:\"channelId\"\:\"//g' \
            -e 's/\"//g' \
            -e 's/content\:horizontalListRenderer\:items\:\[gridChannelRenderer\:channelId\://g' \
            -e 's/content\:expandedShelfContentsRenderer\:items\:\[channelRenderer\:channelId\://g' \
    )

	printf "https://www.youtube.com/feeds/videos.xml?channel_id=$CHANNEL_ID\n"
done

exit 0
